#!/bin/bash

# NBA 20230104: Simple script to connect your Freeox API 
# This let you use functions from fbx-delta-nba_bash_api.sh directly from your bash terminal

source ./fbx-delta-nba_bash_api.sh

MY_APP_ID="MyShellApp"
MY_APP_TOKEN="Here_you_must_put_the_for_MyShellApp_obtained_with_function_authorize_application"

login_freebox "$MY_APP_ID" "$MY_APP_TOKEN"

